config/routes.rb
Rails.application.routes.draw do
  resources :bedsitters
  resources :apartments

end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
end

app/models/bedsitter.rb
class Bedsitter < ActiveRecord::Base
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:space_type, :street, :residence)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bedsitters_controller.rb
class BedsittersController < ApplicationController
  before_action :set_bedsitter, only: [:show, :edit, :update, :destroy]

  # GET /bedsitters
  # GET /bedsitters.json
  def index
    @bedsitters = Bedsitter.all
  end

  # GET /bedsitters/1
  # GET /bedsitters/1.json
  def show
  end

  # GET /bedsitters/new
  def new
    @bedsitter = Bedsitter.new
  end

  # GET /bedsitters/1/edit
  def edit
  end

  # POST /bedsitters
  # POST /bedsitters.json
  def create
    @bedsitter = Bedsitter.new(bedsitter_params)

    respond_to do |format|
      if @bedsitter.save
        format.html { redirect_to @bedsitter, notice: 'Bedsitter was successfully created.' }
        format.json { render :show, status: :created, location: @bedsitter }
      else
        format.html { render :new }
        format.json { render json: @bedsitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bedsitters/1
  # PATCH/PUT /bedsitters/1.json
  def update
    respond_to do |format|
      if @bedsitter.update(bedsitter_params)
        format.html { redirect_to @bedsitter, notice: 'Bedsitter was successfully updated.' }
        format.json { render :show, status: :ok, location: @bedsitter }
      else
        format.html { render :edit }
        format.json { render json: @bedsitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bedsitters/1
  # DELETE /bedsitters/1.json
  def destroy
    @bedsitter.destroy
    respond_to do |format|
      format.html { redirect_to bedsitters_url, notice: 'Bedsitter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bedsitter
      @bedsitter = Bedsitter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bedsitter_params
      params.require(:bedsitter).permit(:type, :street, :residence)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bedsitters_helper.rb
module BedsittersHelper
end

app/views/apartments/_form.html.erb
<%= form_for(@apartment) do |f| %>
  <% if @apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% @apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form class="col s12">
<div class="input-field col s12">
  <label for="Space_type"> <%= f.label :type %><br> </label>
  <input placeholder="Placeholder" type="text" class="validate" <%= f.text_field :type %> >      
</div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :residence %><br>
    <%= f.text_field :residence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</form>

app/views/apartments/edit.html.erb
<h1>Editing Apartment</h1>

<%= render 'form' %>

<%= link_to 'Show', @apartment %> |
<%= link_to 'Back', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apartments</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Street</th>
      <th>Residence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.type %></td>
        <td><%= apartment.street %></td>
        <td><%= apartment.residence %></td>
        <td><%= link_to 'Show', apartment %></td>
        <td><%= link_to 'Edit', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Destroy', apartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Apartment', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>New Apartment</h1>

<%= render 'form' %>

<%= link_to 'Back', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @apartment.type %>
</p>

<p>
  <strong>Street:</strong>
  <%= @apartment.street %>
</p>

<p>
  <strong>Residence:</strong>
  <%= @apartment.residence %>
</p>

<%= link_to 'Edit', edit_apartment_path(@apartment) %> |
<%= link_to 'Back', apartments_path %>

app/views/bedsitters/_form.html.erb
<%= form_for(@bedsitter) do |f| %>
  <% if @bedsitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bedsitter.errors.count, "error") %> prohibited this bedsitter from being saved:</h2>

      <ul>
      <% @bedsitter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :residence %><br>
    <%= f.text_field :residence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bedsitters/edit.html.erb
<h1>Editing Bedsitter</h1>

<%= render 'form' %>

<%= link_to 'Show', @bedsitter %> |
<%= link_to 'Back', bedsitters_path %>

app/views/bedsitters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bedsitters</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Street</th>
      <th>Residence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bedsitters.each do |bedsitter| %>
      <tr>
        <td><%= bedsitter.type %></td>
        <td><%= bedsitter.street %></td>
        <td><%= bedsitter.residence %></td>
        <td><%= link_to 'Show', bedsitter %></td>
        <td><%= link_to 'Edit', edit_bedsitter_path(bedsitter) %></td>
        <td><%= link_to 'Destroy', bedsitter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bedsitter', new_bedsitter_path %>

app/views/bedsitters/new.html.erb
<h1>New Bedsitter</h1>

<%= render 'form' %>

<%= link_to 'Back', bedsitters_path %>

app/views/bedsitters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @bedsitter.type %>
</p>

<p>
  <strong>Street:</strong>
  <%= @bedsitter.street %>
</p>

<p>
  <strong>Residence:</strong>
  <%= @bedsitter.residence %>
</p>

<%= link_to 'Edit', edit_bedsitter_path(@bedsitter) %> |
<%= link_to 'Back', bedsitters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Idealspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Logo</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="All Properties">Sass</a></li>
        <li><a href="Apartments">Components</a></li>
        <li><a href="Bedsitters">JavaScript</a></li>
      </ul>
    </div>
  </nav>
</div>
  <%= yield %>
</body>
</html>